parameters:
  - name: environment
    type: string
  - name: deploymentName
    type: string
  - name: approvalNotifyUsers
    type: string
    default: |
      test@abc.com
      test1@abc.com

jobs:
  - job: ProductionApproval
    displayName: Approve or reject ${{ parameters.deploymentName }} production deployment
    pool: server
    timeoutInMinutes: 1450
    steps:
      - task: ManualValidation@0
        displayName: Approve or decline ${{ parameters.deploymentName }} production deployment
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: ${{ parameters.approvalNotifyUsers }}
          instructions: Approve ${{ upper(parameters.environment) }} ${{ parameters.deploymentName }} deployment
          onTimeout: reject