parameters:
- name: environment
  type: string
- name: tfvarsFile
  type: string

jobs:
- job: Plan
  displayName: Validate, scan and plan
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - template: ../steps/terraform-init.yaml
    parameters:
      environment: ${{ parameters.environment }}
  - template: ../steps/terraform-plan.yaml
    parameters:
      environment: ${{ parameters.environment }}
      tfvarsFile: ${{ parameters.tfvarsFile }}
