apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-storageaccount
  annotations: 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Release.Name }}-storageaccount-exchange
      type: Opaque
      data:
        - objectName: azurestorageaccountname-files
          key: azurestorageaccountname
        - objectName: azurestorageaccountkey-files
          key: azurestorageaccountkey
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.serviceAccountClientId }}
    keyvaultName: {{ .Values.kv.keyVaultName }}
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |          
          objectName: azurestorageaccountname-files
          objectType: secret
        - |
          objectName: azurestorageaccountkey-files
          objectType: secret
    tenantId: {{ .Values.kv.tenantId }}
