trigger:
  branches:
    include: [main]
  paths:
    include: [terraform/**, pipelines/terraform.yml, pipelines/templates/**, pipelines/jobs/**, pipelines/steps/**]

parameters:
- name: environment
  type: string
  default: dev
  values: [dev, test, prod]
- name: apply
  type: boolean
  default: false

variables:
- name: azureServiceConnection
  value: kk-azure-main-299563fd58684ab7
- name: backendResourceGroup
  value: kml_rg_main-299563fd58684ab7
- name: backendStorageAccount
  value: demoappstg
- name: backendContainer
  value: tfstate

stages:
- template: templates/terraform.yaml
  parameters:
    environment: ${{ parameters.environment }}
    apply: ${{ parameters.apply }}
